### ISSUE TITLE
Unreachable code is not marked as error in the c-editor

### ISSUE THREAD

**Issue by JonasWoh** [Skypr/BEAST#44]

**Comment by Skypr** [comment]
I think we are unable to fix this issue, when even gcc says that they wont do it.
(for reference http://gcc.gnu.org/ml/gcc-help/2011-05/msg00360.html)
We are already using a compiler to check the code for errors, therefore I don't think that adding functionality to check for unreachable code will be trivial, if compiling doesn't provide them

**Comment by Skypr** [comment]
After thinking about this issue again, I will close it, because C doesn't care about unreachable code, and our program never intended to be a full IDE
